// Generated by CoffeeScript 1.6.3
(function() {
  var type;

  type = require('./type');

  console.log(type(" ") === 'string');

  console.log(type(new String) === 'string');

  console.log(type([]) === 'array');

}).call(this);
